# If you change the FLASK_PORT, do not forget to change it in ports and healthcheck as well.
services:
  FanFicEpubGeneratorr:
    image: ghcr.io/CalvesGEH/FanFicEpubGenerator:latest
    environment:
      INGEST_DIR: /cwa-book-ingest
      ROYAL_ROAD_DOWNLOAD_FOLLOWS: False
      ROYAL_ROAD_EMAIL: <YOUR_ROYALROAD_EMAIL>
      ROYAL_ROAD_PASSWORD: <YOUR_ROYALROAD_PASSWORD>
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /tmp/data/calibre-web/ingest:${INGEST_DIR:-/cwa-book-ingest}

  cloudflarebypassforscraping:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: unless-stopped